### ISSUE TITLE
Great job. is there a linux version?

### ISSUE THREAD

**Issue by cscaloni** [blehnen/TvHeadEndM3uProxy#3]
Hi!

in the first place, congrats for your job and thanks for sharing it

It works fine on windows, but i am looking for the same but on linux, to have a daemon in the own server

Do you have an alternative for linux?

Thanks you very much in advance

**Comment by blehnen** [comment]
Hi,

I've added very basic support for Linux.  I don't use Linux myself for hobby projects and so I'm not entirely sure what I've added is correct.

I've tested this under WSL2 using Ubuntu 22.04.2.  You'll need to use the dot.net 6 binary (which is new with the last set of changes)

dotnet TvHeadEndM3uProxy.dll

That being said, its running as a console application more or less.  I think it can be demonized, but I've not tried.
